language: c

dist: trusty
sudo: required

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      valgrind
      cloc

install:
  - travis_retry wget https://cmake.org/files/v3.11/cmake-3.11.1-Linux-x86_64.sh
  - sudo bash cmake-3.11.1-Linux-x86_64.sh --skip-license --exclude-subdir --prefix=/usr/local
  - export PATH="/usr/local/bin:$PATH"
  - mkdir -p $HOME/protobuf && pushd $HOME/protobuf
    && wget 'https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip' -O protoc-3.6.1-linux-x86_64.zip
    && unzip protoc-3.6.1-linux-x86_64.zip -d protoc-3.6.1-linux-x86_64
    && popd
  - pushd $HOME/protobuf
    && wget 'https://github.com/google/protobuf/releases/download/v3.6.1/protobuf-python-3.6.1.tar.gz' -O protobuf-python-3.6.1.tar.gz
    && tar xzf protobuf-python-3.6.1.tar.gz
    && cp protoc-3.6.1-linux-x86_64/bin/protoc protobuf-3.6.1/src/
    && pushd protobuf-3.6.1/python
    && python setup.py build && sudo python setup.py install
    && popd
    && popd

before_script:
  - ${CC} --version
  - cmake --version
  - valgrind --version

script:
  - cmake -H. -Bbuild -DVIRGIL_LIB_RATCHET=ON -DCMAKE_INSTALL_PREFIX=install
  - cmake --build build -- -j8
    && pushd build
    && ctest -T memcheck --verbose
    && cat Testing/Temporary/MemoryChecker.*.log
    && popd

after_success:
  - cmake --build build --target cloc
