/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class virgil_crypto_pythia_PythiaJNI */

#ifndef _Included_virgil_crypto_pythia_PythiaJNI
#define _Included_virgil_crypto_pythia_PythiaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     virgil_crypto_pythia_PythiaJNI
 * Method:    pythia_globalInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_virgil_crypto_pythia_PythiaJNI_pythia_1globalInit
  (JNIEnv *, jobject);

/*
 * Class:     virgil_crypto_pythia_PythiaJNI
 * Method:    pythia_globalCleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_virgil_crypto_pythia_PythiaJNI_pythia_1globalCleanup
  (JNIEnv *, jobject);

/*
 * Class:     virgil_crypto_pythia_PythiaJNI
 * Method:    pythia_blindedPasswordBufLen
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_virgil_crypto_pythia_PythiaJNI_pythia_1blindedPasswordBufLen
  (JNIEnv *, jobject);

/*
 * Class:     virgil_crypto_pythia_PythiaJNI
 * Method:    pythia_deblindedPasswordBufLen
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_virgil_crypto_pythia_PythiaJNI_pythia_1deblindedPasswordBufLen
  (JNIEnv *, jobject);

/*
 * Class:     virgil_crypto_pythia_PythiaJNI
 * Method:    pythia_blindingSecretBufLen
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_virgil_crypto_pythia_PythiaJNI_pythia_1blindingSecretBufLen
  (JNIEnv *, jobject);

/*
 * Class:     virgil_crypto_pythia_PythiaJNI
 * Method:    pythia_transformationPrivateKeyBufLen
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_virgil_crypto_pythia_PythiaJNI_pythia_1transformationPrivateKeyBufLen
  (JNIEnv *, jobject);

/*
 * Class:     virgil_crypto_pythia_PythiaJNI
 * Method:    pythia_transformationPublicKeyBufLen
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_virgil_crypto_pythia_PythiaJNI_pythia_1transformationPublicKeyBufLen
  (JNIEnv *, jobject);

/*
 * Class:     virgil_crypto_pythia_PythiaJNI
 * Method:    pythia_transformedPasswordBufLen
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_virgil_crypto_pythia_PythiaJNI_pythia_1transformedPasswordBufLen
  (JNIEnv *, jobject);

/*
 * Class:     virgil_crypto_pythia_PythiaJNI
 * Method:    pythia_transformedTweakBufLen
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_virgil_crypto_pythia_PythiaJNI_pythia_1transformedTweakBufLen
  (JNIEnv *, jobject);

/*
 * Class:     virgil_crypto_pythia_PythiaJNI
 * Method:    pythia_proofValueBufLen
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_virgil_crypto_pythia_PythiaJNI_pythia_1proofValueBufLen
  (JNIEnv *, jobject);

/*
 * Class:     virgil_crypto_pythia_PythiaJNI
 * Method:    pythia_passwordUpdateTokenBufLen
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_virgil_crypto_pythia_PythiaJNI_pythia_1passwordUpdateTokenBufLen
  (JNIEnv *, jobject);

/*
 * Class:     virgil_crypto_pythia_PythiaJNI
 * Method:    pythia_blind
 * Signature: (J[B)Lvirgil/crypto/pythia/PythiaBlindResult;
 */
JNIEXPORT jobject JNICALL Java_virgil_crypto_pythia_PythiaJNI_pythia_1blind
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     virgil_crypto_pythia_PythiaJNI
 * Method:    pythia_deblind
 * Signature: (J[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_virgil_crypto_pythia_PythiaJNI_pythia_1deblind
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     virgil_crypto_pythia_PythiaJNI
 * Method:    pythia_computeTransformationKeyPair
 * Signature: (J[B[B[B)Lvirgil/crypto/pythia/PythiaComputeTransformationKeyPairResult;
 */
JNIEXPORT jobject JNICALL Java_virgil_crypto_pythia_PythiaJNI_pythia_1computeTransformationKeyPair
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     virgil_crypto_pythia_PythiaJNI
 * Method:    pythia_transform
 * Signature: (J[B[B[B)Lvirgil/crypto/pythia/PythiaTransformResult;
 */
JNIEXPORT jobject JNICALL Java_virgil_crypto_pythia_PythiaJNI_pythia_1transform
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     virgil_crypto_pythia_PythiaJNI
 * Method:    pythia_prove
 * Signature: (J[B[B[B[B[B)Lvirgil/crypto/pythia/PythiaProveResult;
 */
JNIEXPORT jobject JNICALL Java_virgil_crypto_pythia_PythiaJNI_pythia_1prove
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     virgil_crypto_pythia_PythiaJNI
 * Method:    pythia_verify
 * Signature: (J[B[B[B[B[B[B)V
 */
JNIEXPORT void JNICALL Java_virgil_crypto_pythia_PythiaJNI_pythia_1verify
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     virgil_crypto_pythia_PythiaJNI
 * Method:    pythia_getPasswordUpdateToken
 * Signature: (J[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_virgil_crypto_pythia_PythiaJNI_pythia_1getPasswordUpdateToken
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     virgil_crypto_pythia_PythiaJNI
 * Method:    pythia_updateDeblindedWithToken
 * Signature: (J[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_virgil_crypto_pythia_PythiaJNI_pythia_1updateDeblindedWithToken
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
